forms/contact.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class ContactForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()], render_kw={"placeholder": "Name"})
    email = StringField("Email", validators=[DataRequired()], render_kw={"placeholder": "Email"})
    message = TextAreaField("Message", validators=[DataRequired()], render_kw={"placeholder": "Message", "rows": 4})
    submit = SubmitField("Send")

forms/signup.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class SignupForm(FlaskForm):
    first_name = StringField("First Name*", validators=[DataRequired()], render_kw={"placeholder": "Frank"})
    last_name = StringField("Last Name*", validators=[DataRequired()], render_kw={"placeholder": "Reynolds"})
    email = StringField("Email*", validators=[DataRequired()], render_kw={"placeholder": "mantis@paddyspub.com"})
    phone = StringField("Phone*", validators=[DataRequired()], render_kw={"placeholder": "(267) 750-9000"})
    company = StringField("Company*", validators=[DataRequired()], render_kw={"placeholder": "Paddy's Pub"})
    submit = SubmitField("Submit")

views/admin/__init__.py
from io import BytesIO

from flask import (
    Blueprint, render_template, request, jsonify, abort, flash, url_for, redirect, json
)
from views.base import requires_admin
from sqlalchemy.exc import IntegrityError
from forms.newchannel import NewchannelForm
from forms.newshow import NewShowForm
from forms.newpromo import NewPromoForm
from forms.newclip import NewClipForm
from flask_login import login_required, logout_user
from forms.password import CreatePassword
from models import db, Users, Channel, Show, Clip, Promo, Loop
from helpers import generate_confirmation_token, confirm_token
from services.google_clients import Gmail, GoogleStorage
from services.imaging import screencap_from_video
from PIL import Image
from urllib import unquote_plus
from base64 import b64encode
from werkzeug.utils import secure_filename
import re
from views.dashboard import crossdomain

admin = Blueprint('admin', __name__, static_folder='../../static')


@admin.route("/")
@login_required
@requires_admin
def index():
    users = Users.query.all()
    return render_template("admin/admin.html", users=users)


@admin.route("/approve_user", methods=["POST"])
@login_required
@requires_admin
def approve_user():
    req = request.get_json()
    existing_user = Users.query.filter_by(email=req["email"]).first()
    if existing_user.confirmed:
        abort(400, "User is confirmed already.")

    # create gmail client
    gmail = Gmail(delegated_user="info@barscreen.tv")
    # generate password token
    password_token = generate_confirmation_token(existing_user.email)

    # Fill in email body and send email
    email_body = """Congratulations you have been approved for a Barscreen account! Below is a link to create a password. Your email will be used for your username. Link: {}""".format(
        url_for('dashboard.confirm_email', token=password_token),
    )
    gmail.send_email(to=existing_user.email,
                     subject="BarScreen Account", body=email_body)
    return jsonify({"success": True})


@admin.route("/confirm/<token>", methods=["GET", "POST"])
@login_required
@requires_admin
def confirm_email(token):
    # make sure token is set based off what type of request we're getting
    if token:
        form = CreatePassword(token=token)
    else:
        form = CreatePassword()
    if not token:
        token = form.token.data
    # try and confirm token, abort to signup if invalid or expired
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', category='danger')
        return redirect(url_for('base.signup'))

    # pull user associated with token
    user = Users.query.filter_by(email=email).first()
    if not user:
        abort(400, 'Invalid token.')
    if user.confirmed:
        flash('Account already confirmed. Please log in.', category="success")
        return redirect(url_for('dashboard.login'))

    # if form submit, add new password to user and redirect them to dashboard
    if request.method == "POST" and form.validate_on_submit():
        user.set_password(form.password.data)
        user.confirmed = True
        db.session.commit()
        flash("Password set successfully.", category="success")
        return redirect(url_for('dashboard.index'))
    return render_template("dashboard/password.html", form=form, token=token)


@admin.route("/user/<user_id>", methods=["GET", "POST"])
@login_required
@requires_admin
def user(user_id):
    current_user = Users.query.filter_by(id=user_id).first()
    if not current_user:
        abort(404, {"error": "User not found"})
    if request.method == 'POST':
        data = {unquote_plus(k.split("=")[0]): unquote_plus(
            k.split("=")[1]) for k in request.get_data().split("&")}
        if data["name"] in ('confirmed', 'ads'):
            if data['value'].lower() == 'false':
                data['value'] = False
            else:
                data['value'] = True
        setattr(current_user, data["name"], data["value"])
        db.session.commit()
        return ''
    return render_template("admin/user.html", current_user=current_user)


@admin.route("/user/<user_id>/<promo_id>", methods=["GET", "POST"])
@login_required
@requires_admin
def promoid(user_id, promo_id):
    """ Specific channel route, allows edits to specified channel. """
    current_promo = Promo.query.filter_by(
        user_id=user_id, id=promo_id).first()
    if not current_promo:
        abort(404, {"error": "No promo by that id. (id:{})".format(promo_id)})
    return render_template("admin/promoid.html", current_promo=current_promo, user_id=user_id)


@admin.route("/user/<user_id>/addpromo", methods=["POST", "GET"])
@login_required
@requires_admin
def addpromo(user_id):
    """ Add Promo route. Adds clip to whatever the current show that is being edited. """
    error = None
    current_user = Users.query.filter_by(id=user_id).first()
    form = NewPromoForm()
    if request.method == "POST" and form.validate_on_submit():
        storage = GoogleStorage()
        try:
            current_user = Users.query.filter_by(id=user_id).first()
            fn = secure_filename(form.clip_file.data.filename)
            url = storage.upload_promo_video(name=fn, file=form.clip_file.data)

            # save vid and get still from it
            form.clip_file.data.save('/tmp/{}'.format(fn))
            image_path = screencap_from_video("/tmp/{}".format(fn))
            still_url = storage.upload_promo_image(
                name=image_path.split("/")[-1], image_data=open(image_path).read())

            current_user.promos.append(Promo(
                name=form.promo_name.data,
                description=form.description.data,
                clip_url=url,
                image_url=still_url,
            ))

            db.session.commit()
        except Exception as err:
            db.session.rollback()
            if 'duplicate key value violates unique constraint' in str(e):
                error = 'show name already registered.'
        flash("Promo Created.", category="success")
    return render_template("admin/addpromo.html", form=form, error=error, current_user=current_user)


@admin.route("/user/<user_id>/addloop")
@login_required
@requires_admin
def addloop(user_id):
    current_user = Users.query.filter_by(id=user_id).first()
    shows = Show.query.all()
    promos = Promo.query.filter_by(user_id=user_id).all()
    return render_template("admin/addloop.html", current_user=current_user, shows=shows, promos=promos)


@admin.route("/user/<user_id>/loop/<loop_id>")
@login_required
@requires_admin
def editloop(user_id, loop_id):
    print("test")
    current_loop = Loop.query.filter_by(id=loop_id).first()
    current_user = Users.query.filter_by(id=user_id).first()
    shows = Show.query.all()
    promos = Promo.query.filter_by(user_id=user_id).all()
    loop_playlist = []
    if not current_loop:
        abort(404, {"error": "No channel by that id. (id:{})".format(loop_id)})
    for i in current_loop.playlist:
        media_id = re.search(r'\d+', i).group()
        if 'promo' in i.lower():
            promo = db.session.query(Promo).filter(Promo.id == media_id).first()
            # if promo
            if not promo:
                continue
            loop_playlist.append({'id':promo.id, 'name':promo.name, 'image_url':promo.image_url, 'type':'promo'})
        else:
            show = Show.query.filter_by(id=media_id).first()
            loop_playlist.append({'id':show.id, 'name':show.name, 'image_url':show.clips[-1].image_url, 'type':'show'})
    return render_template("admin/editloop.html", loop_playlist=json.dumps(loop_playlist), current_loop=current_loop, current_user=current_user, shows=shows, promos=promos)


@admin.route("/submit_loop", methods=["POST", "PUT"])
@login_required
def submit_loop():
    req = request.get_json()
    current_user = Users.query.filter_by(id=req["user_id"]).first()
    image_url = None
    if req.get("image_data"):
        # write file locally
        with open("/tmp/uploaded_image.png", "wb") as f:
            f.write(req["image_data"].split(",")[-1].decode("base64"))
        # upload file to cdn
        storage = GoogleStorage()
        image_url = storage.upload_loop_image(req["name"] + ".png", open("/tmp/uploaded_image.png").read())
    if request.method == "POST":
        # write file locally
        try:
            current_user.loops.append(Loop(
                name=req["name"],
                playlist=req["playlist"],
                image_url=image_url
            ))
            db.session.commit()
        except Exception as err:
            abort(400, err)
    if request.method == "PUT":
        loop = Loop.query.filter_by(id=req["loop_id"]).first()
        if req["name"] != loop.name:
            loop.name = req["name"]
        if req["playlist"] != loop.playlist:
            loop.playlist = req["playlist"]
        if image_url and image_url != loop.image_url:
            loop.image_url = image_url
        db.session.commit()
    return jsonify({"success": True})


@admin.route("/channels")
@login_required
@requires_admin
def channels():
    """ Route for viewing all channels """
    channels = Channel.query.all()
    return render_template("admin/channels.html", channels=channels)


@admin.route("/channels/<channel_id>", methods=["GET", "POST"])
@login_required
@requires_admin
def channelid(channel_id):
    """ Specific channel route, allows edits to specified channel. """
    current_channel = Channel.query.filter_by(id=channel_id).first()
    if not current_channel:
        abort(404, {"error": "No channel by that id. (id:{})".format(channel_id)})
    return render_template("admin/channelid.html", current_channel=current_channel)


@admin.route("/channels/<channel_id>/<show_id>", methods=["GET", "POST"])
@login_required
@requires_admin
def showid(channel_id, show_id):
    """ Specific channel route, allows edits to specified channel. """

views/base.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import current_user
from forms.contact import ContactForm
from forms.signup import SignupForm
from services.google_clients import Gmail
from models import Users, db
from sqlalchemy.exc import IntegrityError
from functools import wraps

base = Blueprint('base', __name__, static_folder='../static')


def requires_admin(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if not current_user.admin:
            flash("Invalid user permissions.")
            return redirect(url_for('dashboard.login'))
        return f(*args, **kwargs)
    return wrapper


@base.route("/")
def index():
    return render_template("index.html")

@base.route("/about", methods=["GET"])
def about():
    return render_template("about.html")

@base.route("/features", methods=["GET"])
def features():
    return render_template("features.html")

@base.route("/contact", methods=["POST", "GET"])
def contact():
    form = ContactForm()
    if request.method == "POST" and form.validate_on_submit():
        g = Gmail(delegated_user="cam@barscreen.tv")
        msg = """
            New Contact Form Submission:
            Name: {}
            Email: {}
            Message: {}""".format(
            form.name.data,
            form.email.data,
            form.message.data,
        )
        g.send_email(to="info@barscreen.tv",
                     subject="New Contact Submission", body=msg)

    return render_template("contact.html", form=form)


@base.route("/signup", methods=["POST", "GET"])
def signup():
    form = SignupForm()
    if request.method == "POST" and form.validate_on_submit():
        try:
            user = Users(
                first_name=form.first_name.data,
                last_name=form.last_name.data,
                phone_number=form.phone.data,
                email=form.email.data,
                company=form.company.data,
            )
            db.session.add(user)
            db.session.commit()
            g = Gmail(delegated_user="cam@barscreen.tv")
            msg = """
                New Sign Up:
                First Name: {}
                Last Name: {}
                Email: {}
                Phone Number: {}
                Company: {}""".format(
                form.first_name.data,
                form.last_name.data,
                form.email.data,
                form.phone.data,
                form.company.data,
            )
            g.send_email(to="info@barscreen.tv",
                         subject="New Sign Up", body=msg)
        except IntegrityError:
            flash("Sorry, a user with that email exists already.", category="error")
        except Exception:
            flash("Unknown error has occurred. Please try again.", category="error")
        flash("Your account is pending, if you are approved we will be in touch with your credentials. Please check email your email.", category="success")
    return render_template("signup.html", form=form)

templates/about.html
{% extends "layout.html" %}
{% block title %}BarScreen - About{% endblock %}
{% block head %}
  {{ super() }}
  <link rel="stylesheet" type="text/css" href="static/styles/about.css">
{% endblock %}
{% block content %}
    <div class="about_splash" id="about">
    </div>
    <div class="section_splash">
      <div class="title">
        <h3>About</h3>
      </div>
    </div>
    <div class="section">
      <div class="text_container">
        <h3 id="about_subtitle">Our team is building the next generation of restaurant entertainment</h3>
        <p>BarScreen is an industry innovator in the fast paced and growing smart TV industry. Our mission is to provide innovative technology solutions to solve problems for restaurants and pubs. We provide one platform that creates an extremely easy to use experience for managers: one smart TV channel, one dashboard, every screen. Our team is dedicated to creating best in class products and backing it with excellent support.</p>
        <p>We are happy to be headquartered in Victoria, British Columbia. Our little hometown has one of the highest restaurant densities in North America, which makes it the perfect location to launch our product. Our services are available across North America, so please reach out or sign up if you would like to know more.</p>
        <p>At BarScreen, we are always looking for new talented members to join our team. If you have a background in digital media or CTV development, you would be a great addition. However, passion and dedication to our vision of helping restaurants is always welcomed. Please contact us with the link below and we will be in contact.</p>
      </div>
    </div>
    <div class="contact_row">
      <div class="contact">
        <h2>Want more information?</h2>
        <a href="{{ url_for('base.contact') }}">
          <button>Contact Us</button>
        </a>
      </div>
    </div>
{% endblock %}

templates/admin_layout.html
<html>

<head>
  {% block head %}
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/style.css') }}">
  <link rel="stylesheet" type="text/css" title="admin" href="{{ url_for('static', filename='styles/admin.css') }}">
  <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css'
    integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
  <link href="{{ url_for('static', filename='styles/hamburger.css') }}" rel="stylesheet">
  <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" type="text/javascript"></script>
  <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='scripts/header.js') }}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='scripts/admin.js') }}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='scripts/loader.js') }}" type="text/javascript"></script>
  <link href="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/jquery-editable/css/jquery-editable.css"
    rel="stylesheet" />
  <script>$.fn.poshytip = { defaults: null }</script>
  <script
    src="//cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/jquery-editable/js/jquery-editable-poshytip.min.js"></script>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  {% endblock %}

<body>
  <div class="site_container">
    <nav>
      <div class="nav_container">
        <div class="site_logo">
          <img class="logo" src="{{ url_for('static', filename='images/barscreenlogo.png') }}">
          <div class="logo_title">
            <span>Admin</span>
          </div>
        </div>
        <button class="hamburger hamburger--minus" type="button">
          <span class="hamburger-box">
            <span class="hamburger-inner"></span>
          </span>
        </button>
        <div class="nav_menu">
          <ul>
            <a href="{{ url_for('admin.index') }}"><li>Users</li></a>
            <a href="{{ url_for('admin.channels') }}"><li>Channels</li></a>
            <a href="{{ url_for('admin.clips') }}"><li>Clips</li></a>
            <a href="{{ url_for('admin.logout') }}"><li>Log Out</li></a>
          </ul>
        </div>
      </div>
    </nav>
    <div id="loader"></div>
    {% with messages = get_flashed_messages() %}
       {% if messages %}
        <div class="flash_message">
          {% for message in messages %}
             <span>{{ message }}</span>
          {% endfor %}
        </div>
       {% endif %}
    {% endwith %}
    <div id="content">
    {% block content %}{% endblock %}
    </div>
  </div>

</html>

templates/contact.html
{% extends "layout.html" %}
{% block title %}BarScreen - Contact{% endblock %}
{% block head %}
  {{ super() }}
  <link rel="stylesheet" type="text/css" href="static/styles/contact.css">
{% endblock %}
{% block content %}
    <div class="contact_splash" id="contact">
    </div>
    <div class="section_splash">
        <div class="title">
            <h3>Contact</h3>
        </div>
    </div>
    <div class="section">
        <div class="two_section">
            <div class="left_section">
                <h3>Drop us a message and we'll get back to you.</h3>
                <div class="contact_item">
                    <h4>Email</h4>
                    <p><a href="info@barscreen.tv">info@barscreen.tv</a></p>
                </div>
                <div class="contact_item">
                    <h4>Phone</h4>
                    <p>+1-778-350-4548</p>
                </div>
                <div class="contact_item">
                    <h4>Address</h4>
                    <p>777 Fort St</p>
                    <p>Victoria, BC</p>
                </div>
            </div>
            <div class="right_section">
                <h3>Contact Form</h3>
                <form method="POST">
                    {{ form.csrf_token }}
                <feildset class="form_name">
                    {{ form.name }}
                <!--<input type="text" id="name" required="required" class="form_input" placeholder="Name"style>-->
                </feildset>
                <feildset class="form_email">
                    {{ form.email }}
                <!--<input type="text" id="email" required="required" placeholder="Email" class="form_input" style>-->
                </feildset>
                    {{ form.message }}
                <feildset class="form_message">
                <!--<textarea name="message" rows="4" cols="40" id="phone" placeholder="Message" required="required" class="form_input"></textarea>-->
                </feildset>
                <feildset class="submit">
                    {{ form.submit }}
                </feildset>
                </form>
            </div>
        </div>
    </div>
    <div class="section">
        <div class="map" style="width: 100%">
            <iframe width="100%" height="300"
                    src="https://maps.google.com/maps?width=100%&amp;height=600&amp;hl=en&amp;q=777%20Forts%20St.+(BarScreen)&amp;ie=UTF8&amp;t=&amp;z=14&amp;iwloc=B&amp;output=embed"
                    frameborder="0" scrolling="no" marginheight="0" marginwidth="0"><a
                    href="https://www.maps.ie/map-my-route/">Plot a route map</a></iframe>
        </div>
    </div>
{% endblock %}

templates/dashboard_layout.html
<html>
<head>
  {% block head %}
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/dashboard.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/loader.css') }}">
  <link href="{{ url_for('static', filename='styles/hamburger.css') }}" rel="stylesheet">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
  <script src="{{ url_for('static', filename='scripts/loader.js') }}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='scripts/header.js') }}" type="text/javascript"></script>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  {% endblock %}
</head>
<body>
  <nav>
    <div class="nav_container">
      <div class="site_logo">
        <img class="logo" src="{{ url_for('static', filename='images/barscreenlogo.png') }}">
      </div>
      <button class="hamburger hamburger--minus" type="button">
        <span class="hamburger-box">
          <span class="hamburger-inner"></span>
        </span>
      </button>
      <div class="nav_menu">
        <ul>
          <a href="{{ url_for('dashboard.index') }}"><li>Dashboard</li></a>
          <a href="{{ url_for('dashboard.loops') }}"><li>Loops</li></a>
          <a class="hamburger_item" href="{{ url_for('dashboard.account') }}"><li>Account</li></a>
          <a class="hamburger_item" href="{{ url_for('dashboard.logout') }}"><li>Log Out</li></a>
        </ul>
      </div>
      <div class="account_icon">
        <a href="{{ url_for('dashboard.account') }}"><i class="fas fa-user"></i></a>
        <a href="{{ url_for('dashboard.logout') }}"><i class="fas fa-sign-out-alt"></i></a>
      </div>
    </div>
  </nav>
  <div class="title_container">
    <h3 class="title">{% block h3title %}{% endblock %}</h3>
  </div>
  <div id="loader"></div>
  {% with messages = get_flashed_messages() %}
     {% if messages %}
      <div class="flash_message">
        {% for message in messages %}
           <span>{{ message }}</span>
        {% endfor %}
      </div>
     {% endif %}
  {% endwith %}
  <div id="content">
  {% block content %}{% endblock %}
  </div>
</body>
</html>

templates/features.html
{% extends "layout.html" %}
{% block title %}BarScreen - Features{% endblock %}
{% block head %}
  {{ super() }}
  <link rel="stylesheet" type="text/css" href="static/styles/features.css">
{% endblock %}
{% block content %}
    <div class="contact_splash" id="contact">
    </div>
    <div class="section_splash">
      <div class="title">
        <h3>Features</h3>
      </div>
    </div>
    <div class="section" id="grid_header">
      <h3>Restaurant Advantage</h3>
    </div>
    <div class="section" id="grid_container">
      <div class="grid_wrapper">
        <div class="grid_box">
          <div class="grid_image">
            <i class="fas fa-tv"></i>
          </div>
          <div class="grid_text">
            <h4>Business Incentive</h4>
            <p>Restaurants earn money from advertisements shown on their TV screens</p>
          </div>
        </div>
        <div class="grid_box">
          <div class="grid_image">
            <i class="fas fa-cog"></i>
          </div>
          <div class="grid_text">
            <h4>Customizable Content</h4>
            <p>Managers can pick the content that is right for their patrons</p>
          </div>
        </div>
        <div class="grid_box">
          <div class="grid_image">
            <i class="fas fa-stopwatch"></i>
          </div>
          <div class="grid_text">
            <h4>Ease of Use</h4>
            <p>Easily create playlists, customize templates and check stats</p>
          </div>
        </div>
        <div class="grid_box">
          <div class="grid_image">
            <i class="fas fa-bullhorn"></i>
          </div>
          <div class="grid_text">
            <h4>Brand Awareness</h4>
            <p>Created branded promotion segments to increase customer engagement</p>
          </div>
        </div>
        <div class="grid_box">
          <div class="grid_image">
            <i class="fas fa-video"></i>
          </div>
          <div class="grid_text">
            <h4>4K Resolution</h4>
            <p>The highest quality definition provides the best picture on all television screens</p>
          </div>
        </div>
      </div>
    </div>
    <div class="section" id="grid_header">
      <h3>Why Advertisers Love Us</h3>
    </div>
    <div class="section" id="grid_container">
      <div class="grid_wrapper">
        <div class="grid_box">
          <div class="grid_image">
            <i class="fas fa-check-square"></i>
          </div>
          <div class="grid_text">
            <h4>Verified Locations</h4>
            <p>We audit and verify all our locations to ensure viewable screens and restaurant traffic</p>
          </div>
        </div>
        <div class="grid_box">
          <div class="grid_image">
            <i class="fas fa-users"></i>
          </div>
          <div class="grid_text">
            <h4>Multiple Views Per Ad</h4>
            <p>Markets acquire a larger audience than traditional video ads resulting in a higher ROI</p>
          </div>
        </div>
        <div class="grid_box">
          <div class="grid_image">
            <i class="fas fa-shield-alt"></i>
          </div>
          <div class="grid_text">
            <h4>Brand Safety</h4>
            <p>Safe content on trusted premium content partners</p>
          </div>
        </div>
      </div>
    </div>
    <div class="contact_row">
      <div class="contact">
        <h2>Want more information?</h2>
        <a href="{{ url_for('base.contact') }}">
          <button>Contact Us</button>
        </a>
      </div>
    </div>
{% endblock %}

templates/index.html
{% extends "layout.html" %}
{% block title %}BarScreen{% endblock %}
{% block head %}
  {{ super() }}
{% endblock %}
{% block content %}
    <div class="splash">
    </div>
    <div class="section_splash">
      <div class="splash_text">
        <h3>The only channel customized</h3>
        <h2>For your restaurant</h2>
        <h4>BarScreen is a smart channel that combines custom promotions, top tier shows and monetization options for pubs and restaurants.</h4>
        <a href="/signup"><button>SIGN UP <i class='fas fa-arrow-right'></i></button></a>
        <p><span>Always Free</span> - Get started in seconds</p>
      </div>
    </div>
    <div class="section">
      <div class="text_container">
        <h2>What makes BarScreen unique?</h2>
        <h3>BarScreen is the first channel to bring a features specifically designed for restaurants and pubs</h3>
      </div>
      <div class="threeset_row">
        <div class="three_item">
          <img src="static/images/content_icon.png" />
          <h3>Premium Content</h3>
          <p>Select local shows from our library of sports, news and coverage of the latest events.</p>
        </div>
        <div class="three_item">
          <img src="static/images/promotion_icon.png" />
          <h3>Promotion Segments</h3>
          <p>Engage with your community by building promtional videos with our custom templates.</p>
        </div>
        <div class="three_item">
          <img src="static/images/advertising_icon.png" />
          <h3>Advertising Revenue</h3>
          <p>We pay you a share of the advertising revenue displayed on your channel.</p>
        </div>
      </div>
    </div>
    <div class="contact_row">
      <div class="contact">
        <h2>Want more information?</h2>
        <a href="/contact">
          <button>Contact Us</button>
        </a>
      </div>
    </div>
{% endblock %}

templates/layout.html
<html>
<head>
  {% block head %}
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="static/styles/style.css">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.7.0/css/all.css' integrity='sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ' crossorigin='anonymous'>
  <link href="static/styles/hamburger.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="static/scripts/header.js"></script>
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  {% endblock %}
</head>
<body>
  <div class="site_container">
    <nav>
      <div class="nav_container">
        <a href="/">
          <div class="site_logo">
            <img class="logo" src="static/images/barscreenlogo.png">
            <div class="logo_title">
              <span>BarScreen</span>
            </div>
          </div>
        </a>
        <button class="hamburger hamburger--minus" type="button">
          <span class="hamburger-box">
            <span class="hamburger-inner"></span>
          </span>
        </button>
        <div class="nav_menu">
          <ul>
            <li><a href="{{ url_for('base.features') }}">Features</a></li>
            <li><a href="{{ url_for('base.about') }}">About</a></li>
            <li><a href="{{ url_for('dashboard.login') }}">Log In</a></li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}
  </div>
  <div class="footer">
    <div class="section">
      <h4><i class="fa fa-copyright"></i> BarScreen 2019</h4>
    </div>
  </div>
</body>
</html>