forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    email = StringField("Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()], render_kw={"class": "password_input"})
    submit = SubmitField("Login")

forms/password.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, SubmitField, HiddenField
from wtforms.validators import DataRequired, EqualTo


class CreatePassword(FlaskForm):
    token = HiddenField("Submit Token", validators=[DataRequired()])
    password = PasswordField("Password",
                             validators=[DataRequired(), EqualTo(fieldname='confirm', message='Passwords must match')])
    confirm = PasswordField('Repeat Password')
    submit = SubmitField("Submit")

views/dashboard/__init__.py
from flask import (
    Blueprint, render_template, request, flash, jsonify, redirect, url_for, abort, json, make_response
)
from flask_login import login_required, login_user, current_user, logout_user
from forms.login import LoginForm
from forms.password import CreatePassword
from forms.dash_newpromo import DashNewPromoForm
from models import Users, db, Channel, Show, Clip, Promo, Loop
from services.imaging import screencap_from_video
from werkzeug.utils import secure_filename
from sqlalchemy.exc import IntegrityError
from services.google_clients import Gmail, GoogleStorage
from helpers import verify_password, confirm_token, generate_confirmation_token, InvalidTokenError
import re
import logging
from flask import current_app as app
from datetime import timedelta
from functools import update_wrapper


dashboard = Blueprint('dashboard', __name__, static_folder='../../static')


def crossdomain(origin=None, methods=None, headers=None, max_age=21600, attach_to_all=True, automatic_options=True):
    """
    Decorator that adds support for CORS to a route.

    origin: Access-Control-Allow-Origin
    methods: Access-Control-Allow-Methods
    headers: Access-Control-Allow-Headers
    max_age: Access-Control-Max-Age
    attach_to_all: Attach CORS headers to responses for all methods
    automatic_options: Handle OPTIONS pre-flight response
    """
    if methods is not None:
        methods = ', '.join(sorted(x.upper() for x in methods))
    if headers is not None and not isinstance(headers, basestring):
        headers = ', '.join(x.upper() for x in headers)
    if not isinstance(origin, basestring):
        origin = ', '.join(origin)
    if isinstance(max_age, timedelta):
        max_age = max_age.total_seconds()

    def get_methods():
        if methods is not None:
            return methods

        options_resp = app.make_default_options_response()
        return options_resp.headers['allow']

    def decorator(f):
        def wrapped_function(*args, **kwargs):
            if automatic_options and request.method == 'OPTIONS':
                resp = app.make_default_options_response()
            else:
                resp = make_response(f(*args, **kwargs))
            if not attach_to_all and request.method != 'OPTIONS':
                return resp

            h = resp.headers

            h['Access-Control-Allow-Origin'] = origin
            h['Access-Control-Allow-Methods'] = get_methods()
            h['Access-Control-Max-Age'] = str(max_age)
            if headers is not None:
                h['Access-Control-Allow-Headers'] = headers

            # Cancel Strict-Transport-Security if still enabled
            h['Strict-Transport-Security'] = 'max-age=0'

            return resp

        f.provide_automatic_options = False
        return update_wrapper(wrapped_function, f)
    return decorator


@dashboard.route("/")
@login_required
def index():
    return render_template("dashboard/dashboard.html")


@dashboard.route("/index")
@login_required
def alt_index():
    return render_template("dashboard/dashboard.html")


@dashboard.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if request.method == "POST" and form.validate_on_submit():
        # try and match user off given email
        matched_user = db.session.query(Users).filter(
            Users.email == form.email.data).first()
        if not matched_user:
            flash("Invalid email or password.", "error")
            return redirect(url_for("dashboard.index"))
        if not matched_user.confirmed:
            flash("User account has not been approved yet.", "error")
            return redirect(url_for("dashboard.index"))
        # double check password matches hash
        if verify_password(matched_user.password, str(form.password.data)):
            login_user(matched_user)
            if matched_user.admin:
                return redirect(url_for("admin.index"))
            return redirect(url_for("dashboard.index"))
        else:
            flash("Invalid email or password.", "error")
    return render_template("dashboard/login.html", form=form)


@dashboard.route("/confirm/<token>", methods=["GET", "POST"])
def confirm_email(token):
    # make sure token is set based off what type of request we're getting
    if token:
        form = CreatePassword(token=token)
    else:
        form = CreatePassword()
    if not token:
        token = form.token.data
    # try and confirm token, abort to signup if invalid or expired
    try:
        email = confirm_token(token)
    except InvalidTokenError:
        flash('The confirmation link is invalid or has expired.', category='danger')
        return redirect(url_for('base.signup'))

    # pull user associated with token
    user = Users.query.filter_by(email=email).first()
    if not user:
        abort(400, 'Invalid token.')

    # if form submit, add new password to user and redirect them to dashboard
    if request.method == "POST" and form.validate_on_submit():
        user.set_password(form.password.data)
        user.confirmed = True
        db.session.commit()
        flash("Password set successfully.", category="success")
        return redirect(url_for('dashboard.index'))
    return render_template("dashboard/password.html", form=form, token=token)


@dashboard.route("/change_password", methods=["POST"])
def change_password():
    req = request.get_json()
    existing_user = Users.query.filter_by(email=req["email"]).first()
    if not existing_user:
        flash("Invalid email. Please try again.")
        return redirect(url_for("dashboard.login"))
    # create gmail client
    gmail = Gmail(delegated_user="info@barscreen.tv")
    # generate password token
    password_token = generate_confirmation_token(existing_user.email)

    # Fill in email body and send email
    email_body = """Please click on the link to reset your BarScreen password. Link: https://dashboard.barscreen.tv{}""".format(
        url_for('dashboard.confirm_email', token=password_token),
    )
    gmail.send_email(to=existing_user.email,
                     subject="BarScreen Account", body=email_body)
    return jsonify({"success": True})


@dashboard.route("/loops")
@login_required
def loops():
    return render_template("dashboard/loops.html")


@dashboard.route("/loops/addloop", methods=["POST", "GET"])
@login_required
def addloop():
    error = None
    trends = Channel.query.order_by(Channel.id.desc()).limit(10).all()
    entertainments = Channel.query.order_by(Channel.id.desc()).filter(
        (Channel.category).like('Entertainment')).all()
    sports = Channel.query.order_by(Channel.id.desc()).filter(
        (Channel.category).like('Sports')).all()
    news = Channel.query.order_by(Channel.id.desc()).filter(
        (Channel.category).like('News')).all()
    form = DashNewPromoForm()
    if request.method == "POST" and form.validate_on_submit():
        storage = GoogleStorage()
        try:
            # Get secure filename from file data.
            fn = secure_filename(form.promo_file.data.filename)
            # Save file locally.
            form.promo_file.data.save('/tmp/' + fn)
            # Get frame from 5 seconds into video and save it locally.
            image_path = screencap_from_video("/tmp/{}".format(fn))

            # save video locally
            url = storage.upload_promo_video(
                name=fn, file=open("/tmp/"+fn))

            screencap_url = storage.upload_promo_image(
                name=image_path.split("/")[-1], image_data=open(image_path).read())

            current_user.promos.append(Promo(
                name=form.promo_name.data,
                description=form.description.data,
                clip_url=url,
                image_url=screencap_url,
            ))

            db.session.commit()
            flash("Promo created successfully.", category="success")

        except Exception as err:
            print(err)
            logging.error(
                "error uploading new loop: {} {}".format(type(err), err))
            flash(
                "Error creating new loop. Please try again in a few minutes", category="error")
    return render_template("dashboard/addloop.html", form=form, error=error, current_user=current_user, trends=trends, entertainments=entertainments, sports=sports, news=news)


@dashboard.route("/submit_loop", methods=["POST", "PUT"])
@login_required
def submit_loop():
    req = request.get_json()
    current_user = Users.query.filter_by(id=req["user_id"]).first()
    image_url = None
    if req.get("image_data"):
        # write file locally
        with open("/tmp/uploaded_image.png", "wb") as f:
            f.write(req["image_data"].split(",")[-1].decode("base64"))
        # upload file to cdn
        storage = GoogleStorage()
        image_url = storage.upload_loop_image(
            req["name"] + ".png", open("/tmp/uploaded_image.png").read())
    if request.method == "POST":
        # write file locally
        try:
            current_user.loops.append(Loop(
                name=req["name"],
                playlist=req["playlist"],
                image_url=image_url
            ))
            db.session.commit()
        except Exception as err:
            abort(400, err)
    if request.method == "PUT":
        loop = Loop.query.filter_by(id=req["loop_id"]).first()
        if req["name"] != loop.name:
            loop.name = req["name"]
        if req["playlist"] != loop.playlist:
            loop.playlist = req["playlist"]
        if image_url and image_url != loop.image_url:
            loop.image_url = image_url
        db.session.commit()
    return jsonify({"success": True})


@dashboard.route("/loops/<loop_id>", methods=["GET", "POST", "DELETE"])
@login_required
def editloop(loop_id):
    current_loop = db.session.query(Loop).filter(Loop.id==loop_id).first()
    if not current_loop:
        abort(404, {"error": "No loop by that id. (id:{})".format(loop_id)})

templates/dashboard/account.html
{% extends "dashboard_layout.html" %}
{% block title %}BarScreen Dashboard - Account{% endblock %}
{% block h3title %}Account{% endblock %}
{% block head %}
  {{ super() }}
  <script>
      var profile_url = "{{url_for('dashboard.editprofile')}}";
      var email_url = "{{url_for('dashboard.editemail')}}";
      var password_url = "{{url_for('dashboard.change_password')}}";
      var user_id = "{{ current_user.id }}";
  </script>
  <script src="{{ url_for('static', filename='scripts/dash_account.js') }}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.15/jquery.mask.min.js"></script>
{% endblock %}
{% block content %}
  <div class="account_info">
    <div class="account_menu">
      <ul>
        <li class="acc_menu_active">Profile</li>
        <li>Login</li>
        <li>Billing</li>
      </ul>
    </div>
    <div class="account_content">
      <div class="account_modal" id="Profile">
        <form>
          <fieldset class="form_cname">
            <label for="fname">First Name</label>
            <input type="text" id="fname" required="required" class="form_input" value="{{ current_user.first_name }}" style>
          </fieldset>
          <fieldset class="form_cname">
            <label for="lname">Last Name</label>
            <input type="text" id="lname" required="required" class="form_input" value="{{ current_user.last_name }}" style>
          </fieldset>
          <fieldset class="form_cname">
            <label for="phone">Phone</label>
            <input type="text" id="phone" required="required" class="form_input" value="{{ current_user.phone_number }}" style>
          </fieldset>
          <button class="dash_button" id="profile_save">Save</button>
        </form>
      </div>
      <div class="account_modal" style="display:none;" id="Login">
        <form>
          <fieldset class="form_cname">
            <label for="fname">Email</label>
            <input type="text" id="email" required="required" class="form_input" value="{{ current_user.email }}" style>
          </fieldset>
          <button class="dash_button" id="email_save">Save</button>
        </form>
          <div class="border_break"></div>
          <h5>Reset the password for this account.</h5>
          <button class="dash_button" id="password_save">Change Password</button>
      </div>
      <div class="account_modal" style="display:none;" id="Billing">
        <p>Please reach out to <a href="mailto:info@barscreen.tv">info@barscreen.tv</a> to sort out the details of your invoicing.</p>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/addloop.html
{% extends "dashboard_layout.html" %}
{% block title %}BarScreen Dashboard - Create Loop{% endblock %}
{% block h3title %}Create Loop{% endblock %}
{% block head %}
  {{ super() }}
  <script src="{{ url_for('static', filename='scripts/loopCreate_pagination.js') }}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='scripts/loopCreate_channel.js') }}" type="text/javascript"></script>
  <script>
      var post_url = "{{url_for('dashboard.get_channel')}}";
      var save_url = "{{url_for('dashboard.submit_loop')}}";
      var user_id = "{{ current_user.id }}";
  </script>
  <link href="https://vjs.zencdn.net/7.5.4/video-js.css" rel="stylesheet">
  <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
{% endblock %}
{% block content %}
  <div class="creation_dashboard">
    <div class="playlist_col">
      <div class="playlist_title">
        <h3>
          <div class="title_input"><input id="title_value" placeholder="Title"/></div>
        </h3>
        <div class="playlist_image">
          <img id="loop_preview"/>
          <canvas id="loop_canvas" width="540" height="405"></canvas>
        </div>
        <button class="dash_button" id="save_button">Save</button>
      </div>
      <div class="playlist_list">
        <ul id="playlist">
        </ul>
      </div>
    </div>

    <div class="content_col">
      <button class="dash_button first_promo add_promo">Add A Custom Promo</button>
      <div class="content_row promo_row">
          <div class="row_title">
            <h3>Custom Promos</h3>
            <button class="dash_button add_promo">Add New</button>
          </div>
          <div class="content_display">
            <div class="contentList_container">
              <ul>
                {% for promo in current_user.promos %}
                <li class="content_item playlist_add">
                  <div class="promo_id">{{ promo.id }}</div>
                  <div class="content_img">
                    <img src="{{ promo.image_url }}">
                  </div>
                  <div class="content_title">
                    <span>{{ promo.name }}</span>
                  </div>
                </li>
                {% endfor %}
              </ul>
            </div>
            <div class="content_more">
              <div class="content_arrow">
                <i class="fas fa-angle-right"></i>
              </div>
            </div>
            <div class="pagination createPagination"></div>
          </div>
      </div>
      <div class="content_row">
        <h3>Content Library</h3>
      </div>
      <div class="content_row">
        <div class="row_title">
          <h4>Trending</h4>
        </div>
        <div class="content_display">
          <div class="contentList_container">
            <ul>
              {% for trend in trends %}
              <li class="content_item content_channel">
                <div class="content_id">{{ trend.id }}</div>
                <div class="content_img">
                  <img src="{{ trend.image_url }}">
                </div>
                <div class="content_title">
                  <span>{{ trend.name }}</span>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="content_more">
            <div class="content_arrow">
              <i class="fas fa-angle-right"></i>
            </div>
          </div>
          <div class="pagination createPagination"></div>
        </div>
      </div>
      <div class="content_row">
        <div class="row_title">
          <h4>News</h4>
        </div>
        <div class="content_display">
          <div class="contentList_container">
            <ul>
              {% for new in news %}
              <li class="content_item content_channel">
                <div class="content_id">{{ new.id }}</div>
                <div class="content_img">
                  <img src="{{ new.image_url }}">
                </div>
                <div class="content_title">
                  <span>{{ new.name }}</span>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="content_more">
            <div class="content_arrow">
              <i class="fas fa-angle-right"></i>
            </div>
          </div>
          <div class="pagination createPagination"></div>
        </div>
      </div>
      <div class="content_row">
        <div class="row_title">
          <h4>Sports</h4>
        </div>
        <div class="content_display">
          <div class="contentList_container">
            <ul>
              {% for sport in sports %}
              <li class="content_item content_channel">
                <div class="content_id">{{ sport.id }}</div>
                <div class="content_img">
                  <img src="{{ sport.image_url }}">
                </div>
                <div class="content_title">
                  <span>{{ sport.name }}</span>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="content_more">
            <div class="content_arrow">
              <i class="fas fa-angle-right"></i>
            </div>
          </div>
          <div class="pagination createPagination"></div>
        </div>
      </div>
      <div class="content_row">
        <div class="row_title">
          <h4>Entertainment</h4>
        </div>
        <div class="content_display">
          <div class="contentList_container">
            <ul>
              {% for entertainment in entertainments %}
              <li class="content_item content_channel">
                <div class="content_id">{{ entertainment.id }}</div>
                <div class="content_img">
                  <img src="{{ entertainment.image_url }}">
                </div>
                <div class="content_title">
                  <span>{{ entertainment.name }}</span>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="content_more">
            <div class="content_arrow">
              <i class="fas fa-angle-right"></i>
            </div>
          </div>
          <div class="pagination createPagination"></div>
        </div>
      </div>
    </div>
  </div>
  <div class ="modal">
    <div class="modal-overlay modal-toggle"></div>
      <div class="modal-wrapper modal-transition">
        <div class="modal_title_container">
          <h4 class="modal_title">Add Promo</h4>
        </div>
        <div class="promo_modal" id="Profile">
          <form method="POST" enctype="multipart/form-data">
            {{ form.csrf_token }}
          <div class="promo_img_preview">
            <fieldset>
              <label for="promo_file">File</label>
              <a><i class="fas fa-upload"></i>File Upload
                {{ form.promo_file }}
              </a>
              <video width="512" height="288" class="promo_video" controls>
                <source type="video/mp4">
              </video>
              <canvas id="promo_canvas" width="512" height="288"></canvas>
            </fieldset>
            <div class="promo_img after_overlay">
              <img id="promo_preview"/>
            </div>
          </div>
          <div class="promo_form_container">
              <fieldset>
                {{ form.promo_name.label }}{{ form.promo_name }}
              </fieldset>
              <fieldset>
                {{ form.description.label }}{{ form.description }}
              </fieldset>
        </div>
        <div class=promo_button>
          <button class="dash_button" id="promo_cancel">Cancel</button>
          {{ form.submit(class_="dash_button") }}
        </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/editloop.html
{% extends "dashboard_layout.html" %}
{% block title %}BarScreen Dashboard - Edit {{ current_loop.name }}{% endblock %}
{% block h3title %}Edit Loop{% endblock %}
{% block head %}
  {{ super() }}
  <script>
      var post_url = "{{url_for('dashboard.get_channel')}}";
      var save_url = "{{url_for('dashboard.submit_loop')}}";
      var user_id = "{{ current_user.id }}";
      var loop_id = "{{ current_loop.id }}";
      var loop_playlist = {{ loop_playlist|safe }};
  </script>
  <script src="{{ url_for('static', filename='scripts/loopCreate_pagination.js') }}" type="text/javascript"></script>
  <script src="{{ url_for('static', filename='scripts/loopEdit_channel.js') }}" type="text/javascript"></script>
  <link href="https://vjs.zencdn.net/7.5.4/video-js.css" rel="stylesheet">
  <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
{% endblock %}
{% block content %}
  <div class="creation_dashboard">
    <div class="playlist_col">
      <div class="playlist_title">
        <h3>
          <div class="title_input"><span style="display:inline-block;">{{ current_loop.name }}</span><input style="display:none;" placeholder="Title"/></div>
          <i id="title_edit1" style="display:inline-block;" class="fas fa-pen"></i>
          <i id="title_edit2" style="display:none;" class="far fa-check-circle"></i>
        </h3>
        <div class="playlist_image">
          <img id="loop_preview"/>
          <canvas id="loop_canvas" width="540" height="405"></canvas>
        </div>
        <button class="dash_button" id="save_button">Save</button>
      </div>
      <div class="playlist_list">
        <ul id="playlist">

        </ul>
      </div>
    </div>

    <div class="content_col">
      <button class="dash_button first_promo add_promo">Add A Custom Promo</button>
      <div class="content_row promo_row">
          <div class="row_title">
            <h3>Custom Promos</h3>
            <button class="dash_button add_promo">Add New</button>
          </div>
          <div class="content_display">
            <div class="contentList_container">
              <ul>
                {% for promo in current_user.promos %}
                <li class="content_item playlist_add">
                  <div class="promo_id">{{ promo.id }}</div>
                  <div class="content_img">
                    <img src="{{ promo.image_url }}">
                  </div>
                  <div class="content_title">
                    <span>{{ promo.name }}</span>
                  </div>
                </li>
                {% endfor %}
              </ul>
            </div>
            <div class="content_more">
              <div class="content_arrow">
                <i class="fas fa-angle-right"></i>
              </div>
            </div>
            <div class="pagination createPagination"></div>
          </div>
      </div>
      <div class="content_row">
        <h3>Content Library</h3>
      </div>
      <div class="content_row">
        <div class="row_title">
          <h4>Trending</h4>
        </div>
        <div class="content_display">
          <div class="contentList_container">
            <ul>
              {% for trend in trends %}
              <li class="content_item content_channel">
                <div class="content_id">{{ trend.id }}</div>
                <div class="content_img">
                  <img src="{{ trend.image_url }}">
                </div>
                <div class="content_title">
                  <span>{{ trend.name }}</span>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="content_more">
            <div class="content_arrow">
              <i class="fas fa-angle-right"></i>
            </div>
          </div>
          <div class="pagination createPagination"></div>
        </div>
      </div>
      <div class="content_row">
        <div class="row_title">
          <h4>News</h4>
        </div>
        <div class="content_display">
          <div class="contentList_container">
            <ul>
              {% for new in news %}
              <li class="content_item content_channel">
                <div class="content_id">{{ new.id }}</div>
                <div class="content_img">
                  <img src="{{ new.image_url }}">
                </div>
                <div class="content_title">
                  <span>{{ new.name }}</span>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="content_more">
            <div class="content_arrow">
              <i class="fas fa-angle-right"></i>
            </div>
          </div>
          <div class="pagination createPagination"></div>
        </div>
      </div>
      <div class="content_row">
        <div class="row_title">
          <h4>Sports</h4>
        </div>
        <div class="content_display">
          <div class="contentList_container">
            <ul>
              {% for sport in sports %}
              <li class="content_item content_channel">
                <div class="content_id">{{ sport.id }}</div>
                <div class="content_img">
                  <img src="{{ sport.image_url }}">
                </div>
                <div class="content_title">
                  <span>{{ sport.name }}</span>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="content_more">
            <div class="content_arrow">
              <i class="fas fa-angle-right"></i>
            </div>
          </div>
          <div class="pagination createPagination"></div>
        </div>
      </div>
      <div class="content_row">
        <div class="row_title">
          <h4>Entertainment</h4>
        </div>
        <div class="content_display">
          <div class="contentList_container">
            <ul>
              {% for entertainment in entertainments %}
              <li class="content_item content_channel">
                <div class="content_id">{{ entertainment.id }}</div>
                <div class="content_img">
                  <img src="{{ entertainment.image_url }}">
                </div>
                <div class="content_title">
                  <span>{{ entertainment.name }}</span>
                </div>
              </li>
              {% endfor %}
            </ul>
          </div>
          <div class="content_more">
            <div class="content_arrow">
              <i class="fas fa-angle-right"></i>
            </div>
          </div>
          <div class="pagination createPagination"></div>
        </div>
      </div>
    </div>
  </div>
  <div class ="modal">
    <div class="modal-overlay modal-toggle"></div>
      <div class="modal-wrapper modal-transition">
        <div class="modal_title_container">
          <h4 class="modal_title">Add Promo</h4>
        </div>
        <div class="promo_modal" id="Profile">
          <form method="POST" enctype="multipart/form-data">
            {{ form.csrf_token }}
          <div class="promo_img_preview">
            <fieldset>
              <label for="promo_file">File</label>
              <a><i class="fas fa-upload"></i>File Upload
                {{ form.promo_file }}
              </a>
              <video width="512" height="288" class="promo_video" controls>
                <source type="video/mp4">
              </video>
              <canvas id="promo_canvas" width="512" height="288"></canvas>
            </fieldset>
            <div class="promo_img after_overlay">
              <img id="promo_preview"/>
            </div>
          </div>
          <div class="promo_form_container">
              <fieldset>
                {{ form.promo_name.label }}{{ form.promo_name }}
              </fieldset>
              <fieldset>
                {{ form.description.label }}{{ form.description }}
              </fieldset>
        </div>
        <div class=promo_button>
          <button class="dash_button" id="promo_cancel">Cancel</button>
          {{ form.submit(class_="dash_button") }}
        </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/dashboard/loops.html
{% extends "dashboard_layout.html" %}
{% block title %}BarScreen Dashboard - Loops{% endblock %}
{% block h3title %}Loops{% endblock %}
{% block head %}
  {{ super() }}
  <script src="{{ url_for('static', filename='scripts/loop_pagination.js') }}" type="text/javascript"></script>
{% endblock %}
{% block content %}
  <div class="createnew_wrapper">
    <div class="createnew">
      <a href="{{ url_for('dashboard.addloop') }}"><button class="dash_button"><i class="fas fa-plus-circle"></i> Add New</button></a>
    </div>
  </div>
  <div class="loops_wrapper">
    <div class="loops_container">
      <ul>
        {% for l in current_user.loops %}
        <a href="{{ url_for('dashboard.editloop', loop_id=l.id) }}">
        <li class="loop_item">
            <div class="loop_image">
              <img src="{{ l.image_url }}">
            </div>

            <div class="loop_title">
              <h3>{{ l.name }}</h3>
              <p>{{ l.playlist|length }}</p>
            </div>
        </li>
        </a>
        {% endfor %}
      </ul>
    </div>
    <div class="pagination">
    </div>
  </div>
{% endblock %}